language: ruby
rvm:
- 2.2.2

install:
- npm install gitbook-cli -g
- gitbook install
- gitbook build
- gem install html-proofer

script: 

- htmlproofer ./_book --empty-alt-ignore true --check-external-hash true --http-status-ignore 503 --url-ignore 'https://img.shields.io/badge/discuss-px4-ff69b4.svg,https://img.shields.io/github/release/PX4/Firmware.svg,https://ninja-build.org/,https://github.com/torvalds/subsurface/blob/a48494d2fbed58c751e9b7e8fbff88582f9b2d02/README#L88-L115,https://download.libsodium.org/doc/,https://www.alfa.com.tw/products_show.php?pc=67&ps=241,http://www.qt.io/download-open-source/#section-6,http://gazebosim.org/tutorials?tut=ros_wrapper_versions#Gazebo7.xseries,https://github.com/PX4/Firmware/blob/master/launch/multi_uav_mavros_sitl.launch#L21-L28,https://github.com/PX4/Firmware/blob/master/launch/multi_uav_mavros_sitl.launch#L85-L93,https://support.intrinsyc.com/attachments/download/1515/Flight_3.1.3_qrlSDK.tgz'


env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true   # speeds up installation of html-proofer